[theme]
base = "light"
primaryColor = "#ED1C24"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f5f6"
textColor = "#3a3a3a"

[server]
maxUploadSize = 50
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
